### ISSUE TITLE
sourcemaps

### ISSUE THREAD

**Issue by lupenium** [liferay/liferay-theme-tasks#18]
I looked at the task build: compile-ruby-sass that option sourceMap is set to false, there is a problem for this option to be customizable?

**Comment by Robert-Frampton** [comment]
It shouldn't be a problem to make it configurable, I will most likely make it an option you pass into the registerTasks method in your theme's gulpfile.js.

**Comment by Robert-Frampton** [comment]
With v1.0.9 you can now pass options to the sass compiler through the registerTask [sassOptions](https://github.com/liferay/liferay-theme-tasks#sassoptions) config object.

So in your theme's gulpfile.js you could do...

```js
liferayThemeTasks.registerTasks({
  gulp: gulp,
  sassOptions: {
    // Options that get passed to either gulp-sass or gulp-ruby-sass
  }
});
```

**Comment by lupenium** [comment]
Thanks, i will try on my liferay themes.
