### ISSUE TITLE
Uninstall a themelet: automatic package.json update

### ISSUE THREAD

**Issue by caneta** [liferay/liferay-theme-tasks#19]
Hi everyone.
In my Liferay 7.0 CE GA1 I've succesfully installed the [lfr-product-menu-animation-themelet](https://github.com/Robert-Frampton/lfr-product-menu-animation-themelet) as described [here](https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/themelets) and everything worked fine.

But how to uninstall it?
I've followed the same steps in the opposite order:
```
gulp extend # and uncheck the themelet
npm uninstall -g lfr-product-menu-animation-themelet
gulp deploy
```
but `gulp status` continue to tell me that the themelet were still in place.

To clean everything up I had to remove manually the themelet dependencies inside `package.json`.

Is there a command that I am missing or the `package.json` update after an uninistall is still to be implemented?

Thanks in advance.

**Comment by Robert-Frampton** [comment]
Hey @caneta 

Running `gulp extend` and unchecking the box should remove the themelet dependencies from the package.json.

What os and node/npm versions are you using?

**Comment by caneta** [comment]
```
user@host:$ uname -a
Linux candubuntu 3.16.0-70-generic #90~14.04.1-Ubuntu SMP Wed Apr 6 22:56:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
user@host:$ node --version
v5.1.0
```
