### ISSUE TITLE
theme deploy broken since 1.3

### ISSUE THREAD

**Issue by kairos666** [liferay/liferay-theme-tasks#25]
upgarding from v1.2.3 to 1.3 trigger this

when building a new theme for v7 (FTL, no themelets) 
no changes just deploying it. --> generate error 500 servlet context

**Comment by kairos666** [comment]
Those variables are missing in init.ftl (inherited from styled parent theme) --> assigning those seems to help but admin panels still have some issues

<#assign user_id = user.getUserId() />
<#assign is_default_user = user.isDefaultUser() />
<#assign is_setup_complete = user.isSetupComplete() />
<#assign user_first_name = user.getFirstName() />
<#assign user_middle_name = user.getMiddleName() />
<#assign user_last_name = user.getLastName() />
<#assign user_name = user.getFullName() />
<#assign is_male = user.isMale() />
<#assign is_female = user.isFemale() />
<#assign user_birthday = user.getBirthday() />
<#assign user_email_address = user.getEmailAddress() />
<#assign language = locale.getLanguage() />
<#assign language_id = user.getLanguageId() />
<#assign w3c_language_id = localeUtil.toW3cLanguageId(theme_display.getLanguageId()) />
<#assign time_zone = user.getTimeZoneId() />
<#assign user_greeting = htmlUtil.escape(user.getGreeting()) />
<#assign user_comments = user.getComments() />
<#assign user_login_ip = user.getLoginIP() />
<#assign user_last_login_ip = user.getLastLoginIP() />

**Comment by Robert-Frampton** [comment]
Hi @kairos666 

It looks like some non-backwards compatible [changes](https://github.com/Robert-Frampton/liferay-portal/commit/46585008f297c4c97cd881fe866c94487b808b68) were merged into the unstyled base theme which supplies the init.ftl file which has caused your issue. 

For a temporary workaround I would recommend adding these variables to your theme's init_custom.ftl file until we can either undo these changes or find another solution.

**Comment by kairos666** [comment]
Hi @Robert-Frampton 

Thanks for the confirmation. 
Will do with the workaround for the time being.
