### ISSUE TITLE
npm install not working under windows

### ISSUE THREAD

**Issue by tmair** [liferay/liferay-theme-tasks#28]
The shrinkwrapping broke the installation of the module in environments other than macos x.

The shrinkwrap file contains the `fsevents` module which will then be installed on windows and breaks the installation process.

This seems to be the problem discussed in https://github.com/npm/npm/issues/6801 and https://github.com/npm/npm/issues/2679

**Comment by TBurk83** [comment]
+1

**Comment by Robert-Frampton** [comment]
Hi @tmair 

Thanks for reporting the issue, fixed with v1.3.3. npm3 was improperly shrinkwraping devDependencies, should be fine now.
