### ISSUE TITLE
Support for Source Maps in SCSS compilation

### ISSUE THREAD

**Issue by yuchi** [liferay/liferay-theme-tasks#29]
While we can specify `sassOptions.sourceMap` to `true` there’s no actual support, given the need for `gulp-sourcemaps` ([see here](https://www.npmjs.com/package/gulp-sass#source-maps)).

Would you accept a PR for this?

**Comment by Robert-Frampton** [comment]
I think it's a good idea, as long as we can make it optional and configurable.

**Comment by yuchi** [comment]
Babel compilation source maps are on by default. If I'd make a pull request what would you expect?

**Comment by yuchi** [comment]
Do you have any update on this? Are you still waiting for contributions?

**Comment by jbalsas** [comment]
I think we got this in... closing here, but in the unforgivable case this is still not the case, please, @yuchi, file a grievance complain at the new [liferay-themes-sdk](https://github.com/liferay/liferay-themes-sdk/issues) location.

Thanks!
