### ISSUE TITLE
Gulp build fails when using Ruby sass on a 7.0 theme

### ISSUE THREAD

**Issue by natecavanaugh** [liferay/liferay-theme-tasks#3]
After running the generator and using the Ruby sass selection for a 7.0 theme, `gulp build` fails.
This is because we're only installing bourbon for running on libsass, but we should install it for both.

**Comment by Robert-Frampton** [comment]
See e7fad046a17232f8627b94c7aad0757c2e0d58ad and da730ab8619074dc8c62c8cd94dd378b1858b011
