### ISSUE TITLE
Generate WAR file name based package name + version meta data

### ISSUE THREAD

**Issue by blzaugg** [liferay/liferay-theme-tasks#30]
Rather than `mytheme-theme.war`, use `mytheme-theme-1.0.0.war`. Based on info from `package.json`.
```json
{
	"name": "mytheme-theme",
	"version": "1.0.0"
}

**Comment by Robert-Frampton** [comment]
See https://github.com/liferay/liferay-theme-tasks#distname

Keep in mind that this will actually change the context path of the theme when you deploy it via the deploy directory.

Also see https://github.com/liferay/liferay-theme-tasks/issues/17

**Comment by blzaugg** [comment]
Moved: https://github.com/Robert-Frampton/liferay-plugin-node-tasks/issues/2

**Comment by blzaugg** [comment]
Ah
