### ISSUE TITLE
Theme dependent on another OSGi bundle: how?

### ISSUE THREAD

**Issue by caneta** [liferay/liferay-theme-tasks#34]
In Liferay 7, If I had a normal OSGi bundle, I could declare a dependency to another bundle writing the following inside its **build.gradle** file:
```
dependencies {
  compile group: "it.mycompany", name: "mycompany.experiment.dev.lib", version: "1.0.0"
}
```
But how to do the same thing for a Liferay 7 theme?
How to make a theme dependent to another OSGi bundle?

I know a theme is an OSGi bundle too, but my problem is that I have no **bnd.bnd** and **build.gradle** files...in addition the build system is Gulp and not Gradle (at least not directly): so how to achieve the same goal for a theme?

Thank you

**Comment by Robert-Frampton** [comment]
Hey @caneta,

In [portal](https://github.com/Robert-Frampton/liferay-portal/tree/master/modules/apps/frontend-theme-porygon) what we do is wrap themes in a module and have a `gradle` task take care of installing the `npm` dependencies and calls `gulp` for building/deploying. That way it has a **bnd.bnd** and **build.gradle** file which should allow you to do what you need.

**Comment by jbalsas** [comment]
Hey @caneta, I'm closing here for now. We're still generating war files for themes, and we currently don't have full OSGi support for them. This will be initially handled on the Liferay side, but it is not a priority at the moment.

If this is critical for you, would you mind to file a new issue in the new repo location at ~[liferay-themes-sdk](https://github.com/liferay/liferay-theme-tasks/issues)~ [liferay-themes-sdk](https://github.com/liferay/liferay-themes-sdk/issues) with your use case so we can analyze it further?

Thanks!

**Comment by caneta** [comment]
Ok, I will.
Little typo: the liferay-themes-**sdk** link above leads to the old liferay-themes-**tasks**/issues list: the correct one should be [liferay-themes-sdk issue list](https://github.com/liferay/liferay-themes-sdk/issues)

**Comment by jbalsas** [comment]
🙈 thanks @caneta, updated the link in my comment :)
