### ISSUE TITLE
deploy / watch on remote server

### ISSUE THREAD

**Issue by ghenadiibatalski** [liferay/liferay-theme-tasks#39]
Hello,

is it possible to deploy/watch on remote server for example via gogo (without local folders)? If we need some folders to be mounted, just let us know, which of them we need to mount and where/how we can configure the folders in a theme project.

Thanks,

Gena

**Comment by jbalsas** [comment]
Hey @ghenadiibatalski, sorry for the very very late response on this :(

Just in case, live deployment is indeed supported using the `--live` param. See [Deploy](https://github.com/liferay/liferay-themes-sdk/tree/master/packages/liferay-theme-tasks#deploy) documentation for more information about it.

Please, file an issue in the new [liferay-themes-sdk](https://github.com/liferay/liferay-themes-sdk/issues) repo if you're having any problems with this.

Thanks!
