### ISSUE TITLE
gulp watch fails in linux

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/liferay-theme-tasks#40]
In Linux, using `gulp watch` in the lastest version of liferay-theme-tasks:

The modifications are being watched correctly. When we run it, the war file from "[liferay_home]/osgi/war" is deleted, the .web_bundle_build directory is generated (with all assets). But as soon as we make any modification, it runs the build and delete the .web_bundle_build directory, which is not created anymore. So all the js and css file requests returns 404.

**Comment by natecavanaugh** [comment]
@Robert-Frampton can you think of any reason why this would happen? Are we doing any sort of symlinking that might result in a hard symlink being created?

@marcoscv-work Which flavor/distro of Linux is this?

**Comment by Robert-Frampton** [comment]
I think this might be from a client that was on an old version of the tools.

@marcoscv-work if this is from the client you emailed me about, can you go ahead and close this issue?

**Comment by marcoscv-work** [comment]
yes @Robert-Frampton it is from that client and I think we can go ahead
