### ISSUE TITLE
Document the "Upgrade" Gulp Task

### ISSUE THREAD

**Issue by blzaugg** [liferay/liferay-theme-tasks#49]

**Comment by mwilliams2014** [comment]
Documented here: https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/7-1/running-the-upgrade-task-for-6-2-themes
and here:
https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/7-1/upgrading-themes-created-with-the-theme-generator
