### ISSUE TITLE
Gulp upgrade should output a nicely formatted report

### ISSUE THREAD

**Issue by natecavanaugh** [liferay/liferay-theme-tasks#5]
Right now, running `gulp upgrade` task, it outputs the warnings and messages as it executes them, meaning that all of the warnings and messages are split up by gulp's own logging messages as it changes tasks.
Instead, we should queue up all of the messages, and output after the tasks have run as a nice report splitting up CSS errors from VM errors, from possibly any other types of errors (and possibly splitting those up by type, such as `Bootstrap Upgrade 2 to 3`, or `Liferay Upgrade 6.2 to 7`).

Depends on #4

**Comment by Robert-Frampton** [comment]
See 537c97b515379dc160e87991a8a75a96c3d0229f
