### ISSUE TITLE
Add support for 7.1 themes

### ISSUE THREAD

**Issue by Robert-Frampton** [liferay/liferay-theme-tasks#58]
Currently the theme tasks are only aware of `6.2` and `7.0` as valid versions of the `liferayTheme.version` property in a theme's `package.json`. We need to ensure that the tools work correctly when set to `7.1`. As well as any other meta data that has references to the version of Portal.

**Comment by izaera** [comment]
@Robert-Frampton do we have any list of what this implies? Is it just allowing the tool to read `7.1` or are 7.1 themes radically different from 7.0 ones?

**Comment by Robert-Frampton** [comment]
Hey @izaera,

There's not really a list. We just need to ensure that the tools work when setting the version property of a theme to `7.1`. We also need to check if there are any conditionals in the tasks that are checking for `7.0`. I believe most (if not all) conditionals are checking for `6.2` ([example](https://github.com/liferay/liferay-theme-tasks/blob/master/tasks/build.js#L164)), so it might not be a problem.

We'll also need to rethink how we are [resolving dependencies](https://github.com/liferay/liferay-theme-tasks/blob/master/lib/version_map.js). With removing 6.2 support however, we might be able to remove this logic altogether since 7.1 and 7.0 themes will depend on similar packages.

**Comment by izaera** [comment]
I guess this could be closed. Now I'm heading to the generator that needs to be changed too -> https://github.com/liferay/generator-liferay-theme/issues/23

**Comment by jbalsas** [comment]
Merged to `develop` via https://github.com/liferay/liferay-theme-tasks/pull/74!
