### ISSUE TITLE
Address issue with r2 choking on Clay/Bootstrap 4

### ISSUE THREAD

**Issue by Robert-Frampton** [liferay/liferay-theme-tasks#59]
When building a theme that implements Clay 2.0, the r2 task seems to choke on something in either Clay or Bootstrap 4.

We need to investigate if this is an issue in one of those libraries or in our fork r2 itself (https://www.npmjs.com/package/liferay-r2).

**Comment by Robert-Frampton** [comment]
On another note, we should probably move https://github.com/jbalsas/R2 to the liferay org, as it's still used by the theme tools. Unless there is a way for the themes in 7.1 to leverage the java based tool in Portal, maybe a servlet filter?

@jbalsas

**Comment by jbalsas** [comment]
We probably can't, we don't have sass compilation in portal anymore, everything gets done at build time. We would need to tap into the java tools if we wanted to leverage it.

We could do something similar to what we have in `metal-tools-soy` to leverage https://github.com/liferay/liferay-portal/tree/master/modules/apps/foundation/frontend-css/frontend-css-rtl-converter via a released artifact: https://repository.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/com.liferay.frontend.css.rtl.converter/

**Comment by Robert-Frampton** [comment]
Well technically the r2 stuff runs post sass compilation. We're just running it on `.css` files in the theme tasks.

**Comment by jbalsas** [comment]
You're totally right! Nevertheless, we don't run it on the server anymore :)

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, @pat270, @marcoscv-work, I think this is happening because we have some kind of issue in `clay`. Based on the css output, from [list-group](https://github.com/liferay/clay/blob/master/src/scss/components/_list-group.scss#L18-L22)

```css
[...]
	.list-group {
		@if ($list-group-box-shadow != null) {
			@include box-shadow(none);
		}
	}
[...]
```

Seems to be producing:

```css
[...]
.list-group {
  border-radius: 0.25rem;
  -webkit-box-shadow:;
  box-shadow:;
  color: #6B6C7E; }
[...]
```

This is likely causing rtl to fail to parse. Makes sense?

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, @pat270, wasn't this already addressed in `clay`?

**Comment by pat270** [comment]
Yes was fixed at https://github.com/liferay/clay/commit/774fd866479bf0d1f2d032f906ac7ed95b6f8a43
