### ISSUE TITLE
Gulp build should only copy the files for the chosen template type

### ISSUE THREAD

**Issue by natecavanaugh** [liferay/liferay-theme-tasks#6]
Currently, `gulp build` copies both FTL and VM files in the templates directory over from `_unstyled`, but it should only copy over the files that apply for the option chosen in the Liferay look and feel settings.

I do think this should only apply to files in the templates directory, though. I can imagine that someone may specify a set of templates for the for the resources importer that use Freemarker (or a mix of Freemarker and Velocity), and we shouldn't try to manage anything outside of templates.

**Comment by Robert-Frampton** [comment]
See a969f05986ac743690977d8d513033f44cbe0fc4
