### ISSUE TITLE
Investigate themelets

### ISSUE THREAD

**Issue by Robert-Frampton** [liferay/liferay-theme-tasks#60]
We should investigate if anyone is using this functionality. If we can remove it we should, it will help us remove some old code and simplify the tools.

If we do, we can also remove the themelet generator from generator-liferay-theme.

**Comment by izaera** [comment]
Hey @Robert-Frampton , why do you think themelets are bad? They look like a quite good idea to reuse fragments of themes... 🤔

Also, the code inside the gulp tasks is not so difficult to maintain, IMO.

/CC @jbalsas @marcoscv-work

**Comment by Robert-Frampton** [comment]
I don't think they are bad. It's just nobody uses them at this point. If nobody found them useful, then we might as well lift the burden of maintaining that functionality.

**Comment by LucyI** [comment]
I have them on my list of things to learn about, just have not had time. They sound very useful actually! If there is a tutorial somewhere I'd appreciate the link...

**Comment by mwilliams2014** [comment]
@Robert-Frampton please keep me in the loop if we decide to lose this functionality. I thought they were useful and a big selling point of the new themes workflow created for 7.0. I didn't realize hardly anyone was using them.

@LucyI  https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/themelets

**Comment by jbalsas** [comment]
I think we haven't showcased them properly and demonstrate its usefulness. That might be one of the reasons. I think we can still give them some time to sink and dedicate some efforts to promote them for a little longer.

In any case, I'll be reaching out to Product to see if we can get some more external visibility on this.

**Comment by jbalsas** [comment]
I'm closing for now, on the assumption that we will keep themelets around. I'll reopen or create a new one if we move on a different direction once we get more data.
