### ISSUE TITLE
gulp watch no run

### ISSUE THREAD

**Issue by AntonioMCV** [liferay/liferay-theme-tasks#64]
When I use gulp watch and scss file is changed, only the first time the watch make a deploy.

Versions:
npm 5.3.0
gulp CLI version 3.9.1
liferay-dxp-digital-enterprise-7.0-sp3
windows 7 Professional

**Comment by jbalsas** [comment]
Hey @AntonioMCV, we're moving this repo to [liferay-themes-sdk](https://github.com/liferay/liferay-themes-sdk). I think we already addressed this in `7.1` but maybe didn't make it back to 7.0. As far as I remember this was on Liferay Portal's wab processing side... could you please verify if this is still an issue and file a ticket in the new location if it is so we can investigate?

Thanks!
