### ISSUE TITLE
gulp kickstart a local theme?

### ISSUE THREAD

**Issue by budkin76** [liferay/liferay-theme-tasks#78]
I've been playing around with the Liferay gulp theme tasks and noticed that the kickstart task only has 3 options:

1. Search globally installed npm modules
2. Search npm registry (published modules)
3. Classic theme  

Has anyone considered adding a 4th option to input a path to a locally developed theme? That would be pretty helpful.

**Comment by jbalsas** [comment]
Hey @budkin76, we're moving this repo to [liferay-themes-sdk](https://github.com/liferay/liferay-themes-sdk). I've filed https://github.com/liferay/liferay-themes-sdk/issues/47 over there so we can track an figure out how to implement it there.

This has been definitely brought up in the past, so we'll see if we can make it happen.

Please, feel free to add any additional feedback over the new issue.

Thanks!
