### ISSUE TITLE
Gulp watch on scss files

### ISSUE THREAD

**Issue by petersiman** [liferay/liferay-theme-tasks#8]
Hi, 
I have tried to override`aui/_variables.scss` file from unstyled theme in my custom theme and deployed it with `gulp deploy`. Everything worked fine and the change was visible on my local Liferay. But after I ran `gulp watch` task, the changes in `aui/_variables.scss` file weren't applied. 

Does the gulp watch task work on SCSS files as well?

shimon

**Comment by vernaillen** [comment]
I noticed the same issue here

**Comment by Robert-Frampton** [comment]
The watch task has since been refactored, and it accounts for sass partials. Closing as this is no longer an issue. Thanks,
