### ISSUE TITLE
Gulp watch:clean EBUSY 

### ISSUE THREAD

**Issue by faragos** [liferay/liferay-theme-tasks#85]
Hey I have a problem with the gulp watch:clean. The first time it works fine, but as soon as I stop the watch and want to start it a again it can't execute the watch:clean, because windows locks the util-bridges.jar.

My workaround so far is to uninstall the theme over the gogoshell, then I can delete the folder by myself.
I get the following error-message:

`EBUSY: resource busy or locked, unlink 'C:\DEV\theme\.web_bundle_build\WEB-INF\lib\util-bridges.jar'
C:\DEV\theme\node_modules\liferay-theme-tasks\tasks\watch.js:53`

Do you have a quick fix for that maybe? Would appreciate it :)

**Comment by denissignoretto** [comment]
I've the same problem, do you solved or did you find a workaround?

**Comment by faragos** [comment]
Nope :/

**Comment by timscottbell** [comment]
I am also facing this issue on Windows. :/

**Comment by jbalsas** [comment]
Hey @faragos, @denissignoretto, @timscottbell, we're moving this project to https://github.com/liferay/liferay-themes-sdk

This has also been reported as https://github.com/liferay/liferay-themes-sdk/issues/18 there and we'll be taking a look shortly.

Closing here... 

Thanks for your patience!
