### ISSUE TITLE
gulp extend themelet: No globally installed themelet found.

### ISSUE THREAD

**Issue by urbandroid** [liferay/liferay-theme-tasks#86]
```
test-theme$ gulp extend
[12:11:12] Using gulpfile wars/test-theme/gulpfile.js
[12:11:12] Starting 'extend'...
? What kind of theme asset would you like to extend? Themelet
? Where would you like to search for themelets? Search globally installed npm mo
dules (development purposes only)
[12:11:19] No globally installed themelet found. Install some with "npm i -g [name]"
[12:11:19] Finished 'extend' after 6.93 s


```
```
echo $NODE_PATH
/home/development/.npm-packages/lib/node_modules
```
```
/home/development/.npm-packages/lib/node_modules$ ls
bower  generator-liferay-theme  gulp  npm  test-themelet  yo 
```

```
/home/development/.npm-packages/lib/node_modules/test-themelet$ ls
node_modules  package.json  src
```
```
$ node -e "console.log(process.env.NODE_PATH)"
/home/development/.npm-packages/lib/node_modules
```
```
$ npm root -g
/home/development/.npm-packages/lib/node_modules

```

test-themelet is non-modified themelet created with liferay-theme-generator
test-theme is non-modified theme created with liferay-theme-generator

via yo liferay-theme

**Comment by jbalsas** [comment]
Hey @urbandroid, sorry we took so long to answer :(

I think this is being tracked both at https://github.com/liferay/liferay-themes-sdk/issues/25 and https://github.com/liferay/liferay-themes-sdk/issues/33.

A common problem here is that some of the published themes or themelets mark compatibility with a specific Liferay Portal version (`6.2`, `7.0`), so they won't get listed when creating a theme for a non-compatible version (`7.1`).

Could you verify if this is either your case, or fixed for you? If it isn't, please, file a new issue in the new [liferay-themes-sdk](https://github.com/liferay/liferay-themes-sdk/issues) repo.

Thanks!
